/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.smwasm.smwasm;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void useSmWasm() {
        SmWasm obj = new SmWasm();
        System.out.println(">>> --- begin test 006 --- (" + obj.sn() + ") ---");
        obj.load("../../../../golang/tinylib/smtinylib.wasm", false);
        obj.load("../../../../../rust/wasm/smlibr/pkg/smlibr_bg.wasm", false);
        obj.load("../../../../../rust/wasm/smlibr2/pkg/smlibr2_bg.wasm", false);

        System.out.println(">>> --- loaded --- (" + obj.sn() + ") ---");

        String strInput = "{\"$usage\":\"smexample.heart.beat\"}";
        String strOutput = obj.call(strInput);
        System.out.println(">>> --- call --- (" + obj.sn() + ") --- " + strInput + " --- " + strOutput);

        long millis = System.currentTimeMillis();
        for (int i = 0; i < 10 * 10000; i++) {
            strInput = "{\"$usage\":\"smtest.heart.beat\"}";
            strOutput = obj.call(strInput);
        }
        long span = System.currentTimeMillis() - millis;
        System.out
                .println(">>> --- span --- (" + obj.sn() + ") --- " + span + " --- " + strInput + " --- " + strOutput);

        System.out.println(">>> --- end app --- (" + obj.sn() + ") ---");

        strInput = "{\"$usage\":\"smtest.wrap.beat\"}";
        strOutput = obj.call(strInput);
        System.out.println(">>> --- call outside sm --- (" + obj.sn() + ") --- " + strInput + " --- " + strOutput);

        strInput = "{\"$usage\":\"smtest.native.beat\"}";
        strOutput = obj.call(strInput);
        System.out.println(">>> --- call outside sm --- (" + obj.sn() + ") --- " + strInput + " --- " + strOutput);

        strInput = "{\"$usage\":\"smtest.third.beat\"}";
        strOutput = obj.call(strInput);
        System.out.println(">>> --- call outside sm --- (" + obj.sn() + ") --- " + strInput + " --- " + strOutput);
    }
}
